# Generated by Django 2.1.1 on 2018-12-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoApps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=100)),
                ('app_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='mostore',
            name='apps',
            field=models.ManyToManyField(to='defapp.MoApps'),
        ),
    ]
