# Generated by Django 2.1.1 on 2018-12-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defapp', '0002_auto_20181204_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moapps',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='moapps',
            name='order',
            field=models.SmallIntegerField(default=1),
        ),
    ]
